on:
  push:
   branches:
     - "main"

jobs:
  run-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Validate JSON schema
        run:  yarn && yarn test