name: validate-schemna
on: [pull_request]
  
jobs:
  run-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate JSON schema
        run:  yarn && yarn test