name: validate-schemna
on: [pull_request]
  
jobs:
  run-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
              git checkout $commit
              echo "run test"
          done
      - name: Validate JSON schema
        working-directory: ./
        run:  pwd && yarn && yarn test