on:
  push:
   tags: 
      - "v[0-9]+\\.[0-9]+\\.[0-9]+" # Official release version tags e.g. v2.0.5
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+" # Release candidate tags e.g. v1.0.3-rc4
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-alpha[0-9]+" # Alpha release testing tags e.g. v0.

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest release tag
        run: |
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            git checkout $LATEST_TAG
      - name: Validate JSON schema
        run:  yarn && yarn test
      - name: authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}        
      - name: Update Firestore Collections
        working-directory: ./
        run: cd ./asset-updater && yarn && node index.js

