on:
  push:
   tags: 
    - "v*.*.*"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    name: Update Firestore
    steps: 
    - name: Update latest version in Firestore
      uses: w9jds/firebase-trigger@master
      with:
        credentials: ${{ secrets.FIRESTORE_CREDENTIALS }}
        databaseUrl: https://umee-wallet.firebaseio.com
        path: supported-assets
