on: push

jobs:
  checkout-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo checked out to latest tag $LATEST_TAG
          git checkout main
  validate-json:
    needs: ['checkout-latest']
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Validate JSON schema
        run:  yarn && cd /home/runner/work/supported-projects/supported-projects &&  yarn test
  authenticate:
    needs: ['validate-json']
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
       - name: Authenticate Google Cloud
         uses: 'google-github-actions/auth@v0'
         with:
           credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  update-firestore:
    needs: ['authenticate']
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Update Firestore Collections
        working-directory: ./
        run: cd ./asset-updater && yarn && node index.js