on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo checked out to latest tag $LATEST_TAG
          git checkout main
      - name: Validate JSON schema
        run:  yarn && yarn test
      - name: authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}        
      - name: Update Firestore Collections
        working-directory: ./
        run: cd ./asset-updater && yarn && node index.js

